# Generated by Django 6.0.2 on 2026-02-22 05:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(help_text="User's first name", max_length=100)),
                ('last_name', models.CharField(help_text="User's last name", max_length=100)),
                ('email', models.EmailField(help_text="User's email address", max_length=255, validators=[django.core.validators.EmailValidator()])),
                ('mobile', models.CharField(help_text="User's mobile number (unique)", max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="Mobile number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this user account is currently active')),
                ('mobile_verified', models.BooleanField(default=False, help_text='Whether the mobile number has been verified')),
                ('email_verified', models.BooleanField(default=False, help_text='Whether the email address has been verified')),
                ('income', models.DecimalField(blank=True, decimal_places=2, help_text="User's monthly income", max_digits=12, null=True)),
                ('estimated_expense', models.DecimalField(blank=True, decimal_places=2, help_text="User's estimated monthly expenses", max_digits=12, null=True)),
                ('created_by', models.UUIDField(blank=True, help_text='User ID who created this end user', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='User ID who last updated this end user', null=True)),
            ],
            options={
                'verbose_name': 'End User',
                'verbose_name_plural': 'End Users',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mobile'], name='endusers_en_mobile_a329d0_idx'), models.Index(fields=['email'], name='endusers_en_email_372f97_idx'), models.Index(fields=['is_active'], name='endusers_en_is_acti_31fe55_idx'), models.Index(fields=['mobile_verified'], name='endusers_en_mobile__1d57cc_idx'), models.Index(fields=['email_verified'], name='endusers_en_email_v_bbae85_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserCategories',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.UUIDField(help_text='User ID who owns this category relationship')),
                ('name', models.CharField(help_text='Denormalized category name for performance', max_length=100)),
                ('category', models.ForeignKey(help_text='Reference to the category', on_delete=django.db.models.deletion.CASCADE, related_name='user_categories', to='categories.category')),
            ],
            options={
                'verbose_name': 'User Category',
                'verbose_name_plural': 'User Categories',
                'ordering': ['user_id', 'name'],
                'indexes': [models.Index(fields=['user_id'], name='endusers_us_user_id_617fde_idx'), models.Index(fields=['user_id', 'category'], name='endusers_us_user_id_0139ec_idx')],
                'unique_together': {('user_id', 'category')},
            },
        ),
    ]
