# Generated by Django 6.0.2 on 2026-02-22 05:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("endusers", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="enduser",
            new_name="endusers_mobile_d96c6d_idx",
            old_name="endusers_en_mobile_a329d0_idx",
        ),
        migrations.RenameIndex(
            model_name="enduser",
            new_name="endusers_email_a2d6ff_idx",
            old_name="endusers_en_email_372f97_idx",
        ),
        migrations.RenameIndex(
            model_name="enduser",
            new_name="endusers_is_acti_1c0aca_idx",
            old_name="endusers_en_is_acti_31fe55_idx",
        ),
        migrations.RenameIndex(
            model_name="enduser",
            new_name="endusers_mobile__d3d900_idx",
            old_name="endusers_en_mobile__1d57cc_idx",
        ),
        migrations.RenameIndex(
            model_name="enduser",
            new_name="endusers_email_v_e766e7_idx",
            old_name="endusers_en_email_v_bbae85_idx",
        ),
        migrations.RenameIndex(
            model_name="usercategories",
            new_name="user_catego_user_id_779464_idx",
            old_name="endusers_us_user_id_617fde_idx",
        ),
        migrations.RenameIndex(
            model_name="usercategories",
            new_name="user_catego_user_id_e13647_idx",
            old_name="endusers_us_user_id_0139ec_idx",
        ),
        migrations.AlterModelTable(
            name="enduser",
            table="endusers",
        ),
        migrations.AlterModelTable(
            name="usercategories",
            table="user_categories",
        ),
    ]
