# Generated by Django 6.0.2 on 2026-03-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endusers', '0004_remove_category_from_usercategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercategories',
            name='name',
            field=models.CharField(help_text='Category name', max_length=100),
        ),
        migrations.AlterField(
            model_name='usercategories',
            name='user_id',
            field=models.UUIDField(help_text='User ID who owns this category'),
        ),
    ]
