# Generated by Django 6.0.2 on 2026-03-16 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endusers', '0006_enduser_available_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enduser',
            name='email',
            field=models.EmailField(help_text="User's email address", max_length=255, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='enduser',
            name='mobile',
            field=models.CharField(help_text="User's mobile number (unique)", max_length=20, validators=[django.core.validators.RegexValidator(message="Mobile number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
