# Generated by Django 6.0.2 on 2026-06-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("endusers", "0008_usermonthlybudget"),
    ]

    operations = [
        migrations.AddField(
            model_name="enduser",
            name="expected_saving",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="User's expected monthly savings",
                max_digits=12,
                null=True,
            ),
        ),
    ]
