# Generated by Django 6.0.2 on 2026-02-22 05:49

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Category name (must be unique)", max_length=100, unique=True
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Whether this category is currently active"
                    ),
                ),
                (
                    "last_update_by",
                    models.UUIDField(
                        blank=True, help_text="User ID who last updated this category", null=True
                    ),
                ),
                (
                    "last_update_at",
                    models.DateTimeField(auto_now=True, help_text="Timestamp of the last update"),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["active"], name="categories__active_98c276_idx"),
                    models.Index(fields=["name"], name="categories__name_e3ad98_idx"),
                ],
            },
        ),
    ]
