# Generated by Django 6.0.2 on 2026-03-16 11:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "categories",
            "0002_rename_categories__active_98c276_idx_categories_active_9b0ad9_idx_and_more",
        ),
        ("endusers", "0007_alter_enduser_email_alter_enduser_mobile"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryTransactions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Cumulative amount (negative for debits, positive for credits)",
                        max_digits=12,
                    ),
                ),
                (
                    "category_id",
                    models.ForeignKey(
                        help_text="Category for these transactions",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_transactions",
                        to="endusers.usercategories",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        help_text="User who owns these transactions",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_transactions",
                        to="endusers.enduser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category Transaction Summary",
                "verbose_name_plural": "Category Transaction Summaries",
                "db_table": "category_transactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user_id"], name="category_tr_user_id_11458d_idx"),
                    models.Index(fields=["category_id"], name="category_tr_categor_5e5e45_idx"),
                    models.Index(
                        fields=["user_id", "category_id"], name="category_tr_user_id_5a90fd_idx"
                    ),
                ],
                "unique_together": {("user_id", "category_id")},
            },
        ),
    ]
