# Generated by Django 6.0.2 on 2026-04-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='user_id',
            field=models.UUIDField(db_index=True, help_text='User ID who owns this transaction'),
        ),
    ]
