# Generated by Django 6.0.2 on 2026-03-05 08:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("endusers", "0005_alter_usercategories_name_and_more"),
        (
            "subcategories",
            "0004_rename_sub_categor_is_acti_4d8f6c_idx_sub_categor_is_acti_bdcb17_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField(help_text="User ID who owns this transaction")),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("CREDIT", "Credit"), ("DEBIT", "Debit"), ("EMI", "EMI")],
                        help_text="Type of transaction (CREDIT, DEBIT, or EMI)",
                        max_length=10,
                    ),
                ),
                (
                    "transaction_with",
                    models.CharField(
                        help_text="Person or entity involved in the transaction", max_length=255
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Transaction amount", max_digits=12
                    ),
                ),
                ("date", models.DateField(help_text="Transaction date")),
                (
                    "transaction_proof",
                    models.FileField(
                        blank=True,
                        help_text="Optional proof document for the transaction",
                        null=True,
                        upload_to="transaction_proofs/%Y/%m/%d/",
                    ),
                ),
                (
                    "emi_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("YEARLY", "Yearly"),
                        ],
                        help_text="EMI payment frequency (only for EMI transactions)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "emi_period",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="EMI period in months (only for EMI transactions)",
                        null=True,
                    ),
                ),
                (
                    "emi_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="EMI installment amount (only for EMI transactions)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "emi_start_date",
                    models.DateField(
                        blank=True,
                        help_text="EMI start date (only for EMI transactions)",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this transaction is currently active"
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, help_text="Soft delete flag")),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User ID who created this transaction", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True, help_text="User ID who last updated this transaction", null=True
                    ),
                ),
                (
                    "sub_category",
                    models.ForeignKey(
                        help_text="Sub-category for this transaction",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="subcategories.subcategory",
                    ),
                ),
                (
                    "user_category",
                    models.ForeignKey(
                        help_text="User category for this transaction",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="endusers.usercategories",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "db_table": "transactions",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(fields=["user_id"], name="transaction_user_id_b5bcfd_idx"),
                    models.Index(fields=["user_id", "date"], name="transaction_user_id_059bf9_idx"),
                    models.Index(fields=["user_category"], name="transaction_user_ca_fcc3c0_idx"),
                    models.Index(fields=["sub_category"], name="transaction_sub_cat_8f2205_idx"),
                    models.Index(
                        fields=["transaction_type"], name="transaction_transac_ddda52_idx"
                    ),
                    models.Index(fields=["is_active"], name="transaction_is_acti_3b71e6_idx"),
                    models.Index(fields=["is_deleted"], name="transaction_is_dele_8cf246_idx"),
                ],
            },
        ),
    ]
