# Generated by Django 6.0.2 on 2026-05-25 12:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wishlist", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wishlist",
            options={
                "ordering": ["-expected_date", "-created_at"],
                "verbose_name": "Wishlist Item",
                "verbose_name_plural": "Wishlist Items",
            },
        ),
        migrations.RenameField(
            model_name="wishlist",
            old_name="date",
            new_name="expected_date",
        ),
    ]
