# Generated by Django 6.0.2 on 2026-06-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wishlist", "0002_alter_wishlist_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist",
            name="description",
            field=models.TextField(blank=True, help_text="Description of the item"),
        ),
    ]
